gemini-testing/testplane

- lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/index.js
> Do not retry all suite tests on single test fail

- package.json
Changelog — https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v404-2016-02-03
> Update to webdriver.io 4.0.4

- .jshintrc
- .travis.yml
- README.md
- lib/reporters/flat.js
- lib/runner/mocha-runner/mocha-adapter.js
- lib/runner/mocha-runner/skip/index.js
- lib/runner/mocha-runner/skip/skip-builder.js
- test/lib/reporter/flat.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/skip/index.js
- test/lib/runner/mocha-runner/skip/skip-builder.js
> Add hermione skip API

- README.md
- lib/defaults.js
> Decrease default waitTimeout value

- README.md
I have replaced TDD terms with BDD terms. Don't forget about BDD Mocha specifics.
And colon was added to JSON listing with browsers params.
> Fix some documentation issues

- package.json
Changelog: https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v410-2016-06-22
> Update webdriver.io to 4.1.0

- README.md
> Fix doc for using of environment variable 'HERMIONE_SKIP_BROWSERS'

- README.md
- lib/constants/runner-events.js
- lib/hermione.js
- lib/reporters/flat.js
- lib/reporters/teamcity.js
- lib/retry-manager/index.js
- lib/runner/index.js
- lib/runner/mocha-runner/proxy-reporter.js
- test/lib/retry-manager/index.js
- test/lib/runner/mocha-runner/proxy-reporter.js
> Fix handling of fails in 'before all' hook

- README.md
> Add more docs about hermione feature

- test/lib/reporter/flat.js
- test/lib/runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
После обновления `sinon`, упали некоторые тесты. Пофиксил это.
@j0tunn, @sipayRT, @eGavr, @tormozz48
> Fix up falied tests

- CHANGELOG.md
- package.json
> Changelog for new version

- README.md
- lib/browser-agent.js
- lib/constants/runner-events.js
- lib/runner/index.js
- test/lib/browser-agent.js
- test/lib/runner/index.js
> Support events 'SESSION_START' and 'SESSION_END'

- lib/reporters/flat.js
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/reporter/flat.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> Do not launch session for skipped tests

- package.json
> fix up glob-extra

- package.json
- test/lib/hermione.js
> Glob extra update

- lib/config-reader.js
- lib/runner/index.js
- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- lib/runner/test-skipper.js
- test/lib/config-reader.js
- test/lib/runner/index.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/test-skipper.js
@j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> Skip browsers option

- lib/browser-pool/basic-pool.js
- lib/browser.js
- test/lib/browser-pool/basic-pool.js
- test/lib/browser.js
@j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> Fix base url

- AUTHORS
- LICENSE
> Update legal information

- lib/plugins.js
- lib/utils.js
- test/lib/plugins.js
@j0tunn, @sipayRT, @tormozz48, @DudaGod
> log correct errors about modules connection

- lib/reporters/flat.js
- test/lib/reporter/flat.js
Now it looks like something like this:
> output file path in flat reporter

- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
#@j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> throw error if tests have the same title

- lib/browser.js
- test/lib/browser.js
@j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> process error from prepareBrowser

- README.md
- lib/browser-agent.js
- test/lib/browser-agent.js
> Implement sending browser id as second argument in SESSION_START and SESSION_END events triggering

- CHANGELOG.md
> Changelog for v0.17.0

- README.md
- lib/browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser.js
- test/lib/config/browser-options.js
> Add option 'sessionQuitTimeout'

- lib/browser.js
- package.json
- test/lib/browser.js
> Add ability to configure timeout for takeScreenshot

- package.json
@eGavr @rostik404 @DudaGod @j0tunn
> Implement changelog auto-generation with standard-version plugin

- README.md
- lib/hermione.js
- lib/runner/index.js
- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/hermione.js
- test/lib/runner/index.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> add api for tests reading

- lib/config/browser-options.js
- test/lib/config/browser-options.js
@j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> fix: correct resolving of baseUrl in config

- README.md
- lib/config/options.js
- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/config/options.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> Add method 'hermione.ctx' to tests API 

- lib/runner/index.js
- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/index.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> Fix 'hermione.ctx' method

- lib/browser.js
- test/lib/browser.js
> fix: Fix url decoration for urls without pathnames

- lib/runner/index.js
- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/index.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> Fix: 'global.hermione' is not defined when reading tests via 'readTests'

- lib/hermione.js
- lib/runner/index.js
- test/lib/hermione.js
- test/lib/runner/index.js
/cc @j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> feat: load plugins and pass events when reading files

- README.md
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> feat: pass mocha suite on 'beforeFileRead' and 'afterFileRead' events

- lib/browser.js
- test/lib/browser.js
> major: make browser.url work like url.resolve

- README.md
- lib/reporters/base.js
- lib/reporters/flat.js
- lib/reporters/plain.js
- lib/reporters/utils/helpers.js
- lib/reporters/utils/icons.js
- test/lib/reporter/flat.js
- test/lib/reporter/plain.js
- test/lib/reporter/utils.js
/cc @j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> feat: add plain reporter

- README.md
- lib/browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser.js
- test/lib/config/browser-options.js
/cc @sipayRT @hatroman @DudaGod
> feat: Add optional "meta" field for browser config

- package.json
- test/lib/browser.js
- test/lib/hermione.js
- test/lib/reporter/flat.js
- test/lib/reporter/plain.js
- test/lib/runner/mocha-runner/index.js
> chore: sinon → 2.x

- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/_mocha/suite.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> fix: handle 'before*' hooks failure correctly

- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-builder.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-builder.js
> refactor: create mocha instances via a builder

- CHANGELOG.md
- README.md
> docs: add info about 'before' and 'beforeEach' hooks

- README.md
- lib/browser-pool/q-browser-pool.js
- lib/config/defaults.js
- lib/config/options-builder.js
- lib/config/options.js
- lib/config/utils.js
- lib/runner/mocha-runner/mocha-adapter.js
- lib/runner/mocha-runner/mocha-builder.js
- test/lib/browser-pool/q-browser-pool.js
- test/lib/config/options.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/mocha-builder.js
/cc @j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> feat: reject session on timeout

- lib/runner/mocha-runner/retry-mocha-runner.js
- test/lib/runner/mocha-runner/retry-mocha-runner.js
> feat: provide the ability to modify retries count from plugins

- README.md
- lib/hermione.js
- test/lib/hermione.js
> feat: add options 'loadPlugins' and 'passthroughEvents' to the API method 'readTests'

- README.md
- lib/hermione.js
- test/lib/hermione.js
> feat: add method 'isFailed' to the API

- lib/runner/mocha-runner/mocha-adapter.js
- lib/runner/mocha-runner/proxy-reporter.js
- test/lib/_mocha/suite.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/proxy-reporter.js
> fix: do not start browser for skipped suites

- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> fix: do not restore existing 'global.hermione' variable

- lib/runner/mocha-runner/mocha-adapter.js
- lib/worker/index.js
- lib/worker/runner/mocha-runner/index.js
- lib/worker/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/worker/index.js
> fix: pass meta info from workers to the main process

- README.md
> docs: running of tests in subprocesses

- lib/worker/index.js
- test/lib/worker/index.js
> fix: option 'grep' fails running of test with exception

- lib/reporters/utils/helpers.js
- test/lib/reporter/flat.js
- test/lib/reporter/plain.js
/cc @j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod
> Extend test error with original selenium error

- README.md
- lib/runner/mocha-runner/mocha-adapter.js
- lib/worker/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/mocha-adapter.js
> feat: forbid using of 'before' and 'after' hooks in tests

- README.md
- lib/base-hermione.js
- lib/hermione.js
- lib/worker/hermione.js
- test/lib/hermione.js
- test/lib/worker/hermione.js
> feat: add method 'isWorker' to the API

- package-lock.json
- package.json
> fix: update webdriver.io fork with keep-alive fix

- lib/browser/commands/assert-view/capture-processors/assert-refs.js
- lib/browser/commands/assert-view/capture-processors/index.js
- lib/browser/commands/assert-view/capture-processors/update-refs.js
- lib/browser/commands/assert-view/index.js
- lib/cli/index.js
- lib/config/runtime-config.js
- lib/hermione.js
- lib/runner/index.js
- lib/worker/index.js
- package-lock.json
- package.json
- test/lib/browser/commands/assert-view/index.js
- test/lib/cli/index.js
- test/lib/config/runtime-config.js
- test/lib/hermione.js
- test/lib/runner/index.js
- test/lib/worker/index.js
сс @sipayRT @rostik404 @j0tunn @DudaGod
> feat: option '--update-refs' for 'assertView' command

- lib/runner/index.js
- test/lib/runner/index.js
// cc @j0tunn @DudaGod @rostik404 @eGavr
> fix: do not retry worker init on fail

- lib/browser/camera.js
- lib/browser/commands/assert-view/capture-processors/index.js
- lib/browser/commands/assert-view/index.js
- lib/browser/existing-browser.js
- package-lock.json
- package.json
- test/lib/browser/camera.js
- test/lib/browser/commands/assert-view/index.js
- test/lib/browser/existing-browser.js
cc @j0tunn @sipayRT @rostik404 @DudaGod 
Пока без тестов и какой-либо документации.
> feat(wip): assert view by selectors

- lib/browser/commands/assert-view/index.js
- lib/browser/existing-browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- package-lock.json
- package.json
- test/lib/browser/commands/assert-view/index.js
- test/lib/config/browser-options.js
> feat: compositeImage

- lib/browser/commands/assert-view/index.js
- package-lock.json
- package.json
- test/lib/browser/commands/assert-view/index.js
cc @j0tunn @sipayRT @DudaGod 
Тесты будут позже.
>  feat: add 'ignoreElements' options to 'assertView' command

- lib/base-hermione.js
- lib/hermione.js
- lib/utils/ipc.js
- lib/worker/constants/runner-events.js
- lib/worker/hermione-facade.js
- lib/worker/hermione.js
- lib/worker/runner/mocha-adapter.js
- package.json
- test/lib/browser/existing-browser.js
- test/lib/worker/hermione-facade.js
- test/lib/worker/hermione.js
- test/lib/worker/runner/mocha-adapter.js
- test/utils.js
* emit "INIT" event in workers
* emit "BEFORE_FILE_READ" with new field "tests". For each of the tests added "hermioneCtx" field.
> emit INIT in workers, extend BEFORE_FILE_READ by tests

- lib/worker/hermione-facade.js
- package-lock.json
- test/lib/worker/hermione-facade.js
Synchronization of the configuration must be performed before the tests are started, because on worker initialization, the master config is not ready yet.
> fix sync config in worker

- README.md
- lib/hermione.js
- lib/runner/index.js
- test/lib/hermione.js
- test/lib/runner/index.js
> Introduce hermione.halt method

- lib/browser/existing-browser.js
- test/lib/browser/existing-browser.js
- test/lib/browser/utils.js
This reverts commit 45a11e764a9f230ffca5602b42a27fbc5de7d50c.
> revert: reset cursor position to 0, 0 before running test

- lib/worker/runner/test-runner/index.js
- test/lib/worker/runner/test-runner/index.js
Reverts gemini-testing/hermione#288
> Revert "feat: reset cursor position to (0, 0) before running test"

- README.md
// cc @DudaGod @rostik404 @eGavr @xrsd
> docs: add assertView documentation

- README.md
- lib/browser/existing-browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser/existing-browser.js
- test/lib/browser/utils.js
- test/lib/config/browser-options.js
> feat: add option 'resetCursor'

- README.md
- lib/browser/commands/index.js
- lib/browser/commands/orientation/index.js
- test/lib/browser/commands/set-orientation/index.js
- test/lib/browser/utils.js
> feat: 'setOrientation' command waits for screen rotate

- lib/browser/existing-browser.js
- lib/worker/runner/browser-pool.js
- test/lib/browser/existing-browser.js
- test/lib/worker/runner/browser-pool.js
> fix: set orientation before each test

- README.md
- lib/browser/new-browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser/new-browser.js
- test/lib/browser/utils.js
- test/lib/config/browser-options.js
> feat: add option 'pageLoadTimeout'

- lib/browser/browser.js
- lib/browser/existing-browser.js
- lib/browser/new-browser.js
- package-lock.json
- test/lib/browser/existing-browser.js
- test/lib/browser/new-browser.js
- test/lib/browser/utils.js
- не пытаемся восстановить размер окна после того, как его кто-то поменял в тесте
- выставляем размер окна перед каждым тестом
> fix: set windowSize before each test instead of resetting it after each test

- README.md
> docs: fix quickstart

- README.md
- lib/browser/new-browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser/new-browser.js
> feat: w3c browsers support

- README.md
- lib/constants/runner-events.js
- lib/runner/index.js
- test/lib/runner/index.js
> feat: add 'END' event

- README.md
- lib/hermione.js
- lib/runner/index.js
- test/lib/hermione.js
- test/lib/runner/index.js
cc @j0tunn 
Тестов новых не писал, так как по факту никакой доп функциональности не добавляется, переносил старые и модуля в модуль.
> feat: add ability to emit test result events from plugins

- README.md
- lib/test-collection.js
- test/lib/test-collection.js
> Add sortTests for TestCollection

- README.md
- lib/config/defaults.js
- lib/config/options.js
- test/lib/config/options.js
> feat(config): add parallelLimit option

- package-lock.json
- package.json
Reverts gemini-testing/hermione#377
cc @sipayRT
> Revert "feat(wdio): update wdio version"

- lib/browser/commands/assert-view/capture-processors/assert-refs.js
- lib/browser/commands/assert-view/errors/image-diff-error.js
- lib/browser/commands/assert-view/index.js
- lib/config/defaults.js
- package-lock.json
- package.json
- test/lib/browser/commands/assert-view/index.js
Не забыть обновить версию gemini-core
> feat: add diff clusters

- README.md
- lib/browser/commands/assert-view/index.js
- package-lock.json
- package.json
- test/lib/browser/commands/assert-view/index.js
Minimal test case: https://nda.ya.ru/3UYCB4
Related PR to `gemini-core`: https://github.com/gemini-testing/gemini-core/pull/51
> feat: add allowViewportOverflow option to assertView

- README.md
- lib/config/browser-options.js
- lib/config/defaults.js
- lib/test-reader/index.js
- lib/test-reader/mocha-test-parser.js
- lib/worker/runner/index.js
- test/lib/_mocha/index.js
- test/lib/config/browser-options.js
- test/lib/test-reader/index.js
- test/lib/test-reader/mocha-test-parser.js
- test/lib/worker/runner/caching-test-parser.js
- test/lib/worker/runner/index.js
- test/lib/worker/runner/test-runner/execution-thread.js
- test/utils.js
New option "testExecTimeout" allows to customize test execution timeout for each browser
> feat: add browser option "testTimeout"

- AUTHORS
- lib/browser/commands/assert-view/index.js
- lib/browser/existing-browser.js
- package-lock.json
- package.json
- test/lib/browser/commands/assert-view/index.js
- test/lib/browser/existing-browser.js
https://github.com/gemini-testing/gemini-core/pull/53
https://nda.ya.ru/3UYieV
> Add screenshotDelay option for assertView

- package-lock.json
- package.json
> feat: update wdio version

- README.md
- lib/runner/browser-runner.js
- lib/runner/index.js
- lib/utils/processor.js
- lib/utils/workers-registry.js
- lib/worker/index.js
- test/lib/runner/browser-runner.js
- test/lib/runner/index.js
- test/lib/runner/test-runner/insistant-test-runner.js
- test/lib/runner/test-runner/regular-test-runner.js
- test/lib/utils/workers-registry.js
- test/lib/worker/index.js
- test/setup.js
Related PR: https://github.com/gemini-testing/html-reporter/pull/224
> feat: add method 'registerWorkers' to Runner

- package-lock.json
- package.json
Add to message selectors on NoSuchSelector error:
```
1) some describe 1 some test 1
in file common.test.js
chrome
✘ Error: An element could not be located on the page using the given search parameters (".search2 .search2__button2").
...
```
> chore: update webdriverio version

- lib/browser/commands/assert-view/index.js
In case when we trying to do some screenshot assert in (before/after)Each section
> fix(assert-view): missed hermioneCtx on assertView execution

- lib/stats.js
- package-lock.json
- package.json
- test/lib/stats.js
Подробнее проблему описал тут - https://github.com/gemini-testing/gemini-core/pull/68. Здесь поддержал логику для нового "правильного" подсчета статистики для каждого браузера.
> fix: increment stats for each test result

- README.md
- lib/test-reader/browser/commands/command.js
- lib/test-reader/browser/commands/index.js
- lib/test-reader/browser/commands/version.js
- lib/test-reader/browser/index.js
- lib/test-reader/mocha-test-parser.js
- test/lib/test-reader/browser/commands/version.js
- test/lib/test-reader/browser/index.js
- test/lib/test-reader/mocha-test-parser.js
- typings/index.d.ts
> Implemented browser version assert

- package-lock.json
- package.json
To 5.3.0 to have prebuilt png-img binaries underhood.
> fix: up gemini-core version

- lib/test-collection.js
For support hermione@3 version.
> fix(test-collection): compare test titles with trim

- README.md
- lib/browser/browser.js
- lib/browser/history/callstack.js
- lib/browser/history/commands.js
- lib/browser/history/index.js
- lib/browser/history/utils.js
- lib/config/browser-options.js
- lib/config/defaults.js
- lib/runner/test-runner/regular-test-runner.js
- lib/worker/runner/test-runner/index.js
- test/lib/browser/existing-browser.js
- test/lib/browser/history/callstack.js
- test/lib/browser/history/commands.js
- test/lib/browser/history/index.js
- test/lib/browser/history/utils.js
- test/lib/browser/new-browser.js
- test/lib/browser/utils.js
- test/lib/config/browser-options.js
- test/lib/runner/test-runner/regular-test-runner.js
- test/lib/worker/runner/test-runner/index.js
- typings/index.d.ts
> feat: Implemented commands-history

- lib/browser/browser.js
- lib/browser/history/index.js
- lib/browser/history/utils.js
- test/lib/browser/existing-browser.js
- test/lib/browser/history/index.js
- test/lib/browser/history/utils.js
- test/lib/browser/new-browser.js
addCommands не поднял выше, потому что в истории появляется много шума про системные вызовы - extendOptions
> fix: do not wrap system commands

- package-lock.json
- package.json
More info about new release - https://github.com/webdriverio/webdriverio/releases/tag/v7.9.0.
Post in blog - https://webdriver.io/blog/2021/07/28/sync-api-deprecation
> chore: update wdio to 7.10.0

- lib/browser/commands/get-config/index.js
- lib/browser/commands/index.js
- test/lib/browser/commands/get-config/index.js
Adds getConfig command to the browser.
> feat: add getConfig to the browser instance

- commitlint.config.js
- lib/browser/history/commands.js
- lib/worker/hermione-facade.js
- package-lock.json
- package.json
Апдейтом uglifyify в gemini-core пофиксил две уязвимости, но пришла еще одна, [тикет им я уже завел](https://github.com/hughsk/uglifyify/issues/101)
```
=== npm audit security report ===                        
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ …
```
> fix: vulnerabilities

- lib/worker/runner/caching-test-parser.js
- lib/worker/runner/sequence-test-parser.js
- lib/worker/runner/simple-test-parser.js
- package.json
- test/lib/worker/runner/caching-test-parser.js
- test/lib/worker/runner/sequence-test-parser.js
- test/lib/worker/runner/simple-test-parser.js
По следам https://github.com/gemini-testing/hermione/pull/670
В воркерах нельзя создавать одновременно больше одного инстанса mocha, т.к. она при парсинге активно использует global
> feat: read tests sequentially in worker

- lib/browser/commands/assert-view/index.js
- test/lib/browser/commands/assert-view/index.js
- Убрал лишнее чтение картинки с файловой системы
- Убрал лишнюю запись текущей картинки (если текущая картинка совпадает с референсом)
> perf: optimize fs operations

- lib/worker/runner/caching-test-parser.js
- test/lib/worker/runner/caching-test-parser.js
Fixes https://github.com/gemini-testing/hermione/issues/698
> fix: fill tests cache synchronously in workers

- typings/webdriverio/index.d.ts
Также обновил пример в коде с чейнинга на `async` `await`
> types: add element assertView types

- package-lock.json
- package.json
- src/utils/logger.js
- test/lib/utils/logger.js
Добавил метку времени без локали перед выводом в консоль, добавил тесты
> feat: add logs timestamp

- README.md
- src/test-reader/browser-test-parser.js
- test/lib/test-reader/browser-test-parser.js
BREAKING CHANGE
Prepare to read files only once
> feat: do not pass browser id on file events

- src/cli/index.js
- src/constants/process-messages.ts
- src/hermione.js
- src/runner/index.js
- src/utils/processor.js
- src/utils/workers-registry.js
- src/worker/hermione-facade.js
- test/src/hermione.js
- test/src/runner/index.js
- test/src/utils/workers-registry.js
- test/src/worker/hermione-facade.js
BREAKING CHANGE: terminate tests execution on unhandled rejection in worker
> fix: handle unhandled rejections

- README.md
- src/config/browser-config.js
- src/test-reader/test-object/configurable-test-object.js
- test/src/config/browser-config.js
- test/src/test-reader/test-object/configurable-test-object.js
BREAKING CHANGE:
- test.id() -> test.id
- suite.id() -> suite.id
> feat: make id a plain property

- src/test-reader/test-object/hook.js
- src/test-reader/test-object/test.js
- src/worker/runner/test-runner/execution-thread.js
- test/src/test-reader/test-object/hook.js
- test/src/test-reader/test-object/test.js
- test/src/worker/runner/test-runner/execution-thread.js
> feat: remove runnable type property

- .github/workflows/node.js.yml
- src/browser/browser.js
- src/browser/existing-browser.js
- src/worker/runner/browser-pool.js
- test/src/browser/existing-browser.js
- test/src/browser/new-browser.js
- test/src/worker/runner/browser-pool.js
Cherry pick to hermione@7 from - https://github.com/gemini-testing/hermione/pull/770
> fix: do not reinit cached browser session in worker

- src/index.ts
- Added type exports for TestCollection and Test
> feat: export TestCollection and Test types

- src/browser/existing-browser.js
- test/src/browser/existing-browser.js
- test/src/browser/utils.js
Cherry pick from - https://github.com/gemini-testing/hermione/pull/813
> fix: correctly disable animations in iframes for ios

- src/browser/existing-browser.js
- test/src/browser/existing-browser.js
> fix: correctly switch between iframes on disable animation (backport to v7)

- package.json
Пофиксил тайпскриптовые тайпинги
> fix: typings

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
- .github/ISSUE_TEMPLATE/2-regression-report.yaml
- .github/ISSUE_TEMPLATE/3-feature-request.yaml
- .github/ISSUE_TEMPLATE/config.yml
How it works: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
> feat: issue templates

- package-lock.json
- package.json
Moreover upgrade node to 18.7.0
> chore: update sharp to 0.33.2 from 0.32.6

- package-lock.json
- package.json
- src/test-reader/test-transformer.ts
Forgot to commit these changes in PR - #851
> chore: add bundle watchder

- src/types/index.ts
> fix: correctly specify "testplaneCtx.assertViewResults" type

- README.md
- src/browser/client-scripts/index.js
- src/utils/errors.ts
Backport fixes from testplane to hermione@8
> fix: correctly screen element after moveTo

- typings/api.d.ts
Backport to hermione@8 from testplane - #941
> fix: types for describe, it

- docs/config.md
TransformRequest example is not working without return statement
> Update transform request doc

- src/browser/commands/assert-view/errors/base-state-error.ts
- src/browser/commands/assert-view/errors/image-diff-error.ts
- src/browser/commands/assert-view/errors/no-ref-image-error.ts
- src/browser/commands/assert-view/index.js
- src/types/index.ts
- src/worker/testplane.ts
- test/src/browser/commands/assert-view/index.js
`refImg` now has `relativePath` property
> feat: add relativePath to refImg

- README.md
> docs: add references to the docs website

- package.json
> chore(package.json): add site url to package.json for npm UI

- src/browser/stacktrace/constants.ts
- src/browser/stacktrace/utils.ts
- src/worker/runner/test-runner/index.js
- test/src/browser/stacktrace/utils.ts
Example:
Before (watch 1-st retry): https://nda.ya.ru/t/G_mhJakm782mKy
After (watch 1-st retry): https://nda.ya.ru/t/pt39trMd782mNQ
> fix: remove extra stack frames

- package-lock.json
- package.json
- update plugins-loader in order to correctly works with pnpm
> chore: update plugins-loader from 1.3.1 to 1.3.4

- src/config/types.ts
https://testplane.io/ru/docs/v8/config/browsers/#passive
> Add passive options to config types

- src/browser-installer/chrome/browser.ts
- src/browser-installer/install.ts
- src/browser-installer/registry/index.ts
- src/browser-installer/resolve-browser-version.ts
- src/browser-installer/run.ts
- src/browser/new-browser.ts
- src/browser/types.ts
- src/constants/config.ts
- src/utils/browser.ts
- test/src/browser-installer/chrome/browser.ts
- test/src/browser-installer/install.ts
- test/src/utils/browser.ts
https://github.com/user-attachments/assets/5c5eb8a8-af75-4eed-b5fe-796dd0df87d7
> feat(local-browsers): add ability to install+run chrome-headless-shell

- src/browser/history/rrweb.ts
Fix bug when we lose some steps in history
> Fix save history mode
