gemini-testing/testplane

- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- lib/runner/mocha-runner/proxy-reporter.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/proxy-reporter.js
После [вот этого коммита](https://github.com/gemini-testing/hermione/commit/f4404d060a58671a6de1ed09d5236416d559504f) параллельный запуск в одном браузере сломался, т.к. порвалась связь `один файл` <-> `одна сессия`, и при каждом старте новой сессии она перетиралась.
Здесь я сместил всю эту логику из `MochaRunner` в `MochaAdapter`, и теперь эта связь восстановлена.
Смотреть, в общем-то, не на что, просто переместил код, с минимальными изменениями
> Move browser and all its related stuff from MochaRunner to MochaAdapter

- lib/runner/mocha-runner/mocha-adapter.js
- lib/runner/mocha-runner/proxy-reporter.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/proxy-reporter.js
Do not use reporterOptions because they will be shared between all adapters
> Fix: do not share reporterOptions between mocha adapters

- lib/hermione.js
- package.json
When I specified `debug` option in the config file, I'll got the following error:
```javascript
TypeError: Object function Q(value) {
// If the object is already a Promise, return it directly.  This enables
// the resolve function to both be used to created references from objects,
// but to tolerably coerce non-promises to promises.
if (Q_isPromise(value)) {
return value;
} else if (isThenable(value)) {
if (!thenables.has(value)) {
thenables.set(value, new Promise(new Thenable(value)));
}
return thenables.get(value);
} else {
return new Promise(new Fulfilled(value));
}
} has no method 'getUnhandledReasons'
```
`hermione` uses q library v2 which doesn't have `getUnhandledReasons` method anymore. 
It seems that `q-debug-mode` is useless now and can be pruned.
/cc @j0tunn
> Q has no method 'getUnhandledReasons'

- README.md
- lib/cli.js
- lib/config-reader.js
- test/lib/config-reader.js
- test/lib/runner/mocha-runner/mocha-adapter.js
Grep string is being passed directly to mocha, mocha will convert it to regexp by itself.
> Pass --grep arg to mocha

- README.md
- lib/hermione.js
- lib/runner/index.js
- lib/tests-reader.js
- test/lib/runner/index.js
- test/lib/tests-reader.js
- test/utils.js
/cc @j0tunn @sipayRT @SwinX 
Теперь в `specs` появилась возможность задавать в каких браузерах и какие тесты необходимо запускать.
**Было:**
```js
module.exports = {
browsers: {
bro1: {},
bro2: {},
bro3: {}
},
specs: [
'common',
'touch-pad',
'touch-phone'
]
};
```
**Стало**:
```js
module.exports = {
browsers: {
bro1: {},
bro2: {},
bro3: {}
},    
specs: [
{files: ['common'], browsers: ['bro1', 'bro2', 'bro3']}, // или {files: ['common']}, или 'common'
{files: ['touch-pad'], browsers: ['bro2']},
{files: ['touch-phone'], browsers: ['bro3']}
]
};
```
-------
* Вынес логику про получение тестов с файловой системы и их обработку в отдельных модуль `tests-reader`, который возвращает следующий формат данных:
```js
{chrome: ['/test1.js', '/test2.js'], opera: ['/test1.js', '/test2.js']}
```
* …
> Support configuration of 'sets'

- lib/retry-manager/index.js
- package.json
- test/lib/retry-manager/index.js
- test/mocha.opts
Linked with supporting of [sets](https://github.com/gemini-testing/hermione/pull/9).
---------
/cc @sipayRT @j0tunn
> Fix retry logic because of new runners' API

- README.md
- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
Логика такая:
* оборачиваем коллбэки для тестов/хуков функцией, которая сохраняет текущий контекст выполнения (собственно сам тест или хук)
* в прототип сессии webdriverio дописываем геттер `executionContext`
> Attach execution context to browser

- lib/reporters/flat.js
- package.json
- test/lib/reporter/flat.js
@j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod 
Теперь информация об упавших и заретраеных тестах выводится в конце и выглядит так:
> Log failed tests at the end of reporter

- README.md
- lib/runner/index.js
- test/lib/runner/index.js
cc @sipayRT @j0tunn 
Изменение необходимо для того, чтобы подписавшись на событие `RUNNER_START` была возможность из плагина триггерить другие события раннера, например, `TEST_FAIL`.
> Support passing of a runner to a handler of 'RUNNER_START' event

- lib/reporters/flat.js
- lib/reporters/utils/test-counter.js
- test/lib/reporter/utils/test-counter.js
cc @sipayRT @j0tunn 
Изменение необходимо, чтобы учитывать случаи, когда для одного и того же теста во время запуска летит два события, например, сначала `TEST_PENDING`, а затем `TEST_FAIL`.
> Implement 'test-counter' for 'flat' reporter

- lib/reporters/flat.js
- test/lib/reporter/flat.js
cc @j0tunn @sipayRT 
Сейчас алгоритм вывода ошибки такой:
Если в тесте есть поле `err`, то пытаемся вывести `err.stack`, иначе просто выводим `err`.
По хорошему надо вот так:
Если в тесте есть `err`, то пытаемся вывести `err.stack` или `err.message`, или `err`, иначе выводим `unknown error`.
Проблема возникла при написании валидатора для скипнутых тестов и интеграции его с `allure`-отчетом.
Если в `allure` прилетает ошибка строкой (из валидатора летела строка), то она не отображается в html-отчете. Чтобы ошибка нормально отобразилось, необходимо наличие поля `message` или `stack`, но если кидать ошибку только с полем `message`, то во `flat`-репортере ошибка отображается как `[Object]`.
> fix logging of errors in 'flat' reporter

- lib/config/browser-options.js
- test/lib/config/browser-options.js
/cc @sipayRT 
Опция `screenshotOnReject` была добавлена случайно. Изначально предполагалось, что пользователь не должен иметь возможности ее выставлять, кроме как через `allure`-отчет, соответственно и смысла нет в опции `screenshotDir`, так как все скриншоты цепляются к `allure`-отчету.
> Remove unnecessary option 'screenshotOnReject' from config

- lib/retry-manager/matcher.js
- matcher will be created for each retry
- test object contains `err` field, which contains huge `screenshot` field
> fix: Do not save whole runnable object - decrease memory leaks

- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/mocha-adapter.js
Сейчас при исключении из обработчика любого события hermione зависает (т.к. mocha внутри падает и не зовет callback).
Я здесь оборачиваю `emit` т.о. чтобы он никогда не бросал исключений, но при этом валил mocha.run
> fix: fail instead of hang on throws from event handlers

- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/_mocha/index.js
- test/lib/_mocha/runnable.js
- test/lib/_mocha/suite.js
- test/lib/_mocha/test.js
- test/lib/runner/mocha-runner/mocha-adapter.js
Implement error handling in `before` and `beforeEach` hooks. 
Fix mocha feature with skipped tests after `beforeEach` hook fail.
@sipayRT 
@j0tunn 
@eGavr 
@rostik404 
@DudaGod
> fix: add correct error handling in before and beforeEach hooks

- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-builder.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-builder.js
@j0tunn JFYI
После того, как мы добавили новый уровень абстракции `MochaBuilder`, я забыл, что надо метод `prepare` прокидывать по иерархии `runner`-ов.
> refactor: correct call of method 'prepare' in the hierarchy of runners

- lib/runner/mocha-runner/index.js
- lib/runner/mocha-runner/mocha-adapter.js
- lib/runner/mocha-runner/single-test-mocha-adapter.js
- test/lib/runner/mocha-runner/index.js
- test/lib/runner/mocha-runner/mocha-adapter.js
- test/lib/runner/mocha-runner/single-test-mocha-adapter.js
> fix: do not run 'before' and 'after' hooks for a skipped suite

- lib/runner/mocha-runner/mocha-adapter.js
- test/lib/_mocha/runnable.js
- test/lib/runner/mocha-runner/mocha-adapter.js
Promise timeout errors will be correctly handled by our wrappers.
Instead of mocha error `timeout of 60000ms exceeded. Ensure the done() callback is being called in this test` there will be q error `Timed out after 60000 ms`
> fix: Replace mocha timeouts with promise timeouts

- lib/runner/mocha-runner/proxy-reporter.js
- lib/runner/mocha-runner/skip/index.js
- test/lib/runner/mocha-runner/proxy-reporter.js
- test/lib/runner/mocha-runner/skip/index.js
cc @j0tunn 
Grand Failure после https://github.com/gemini-testing/hermione/pull/146
```js
// Имеем два браузера 'bro1' и 'bro2' в конфиге
describe('suite', () => {
it('test1', () => {
// ...
});
hermione.only.in('bro2')
it('test2', () => {
// ...
});
});
```
В таком случае `test1` не запускается в `bro1`, хотя должен.
-------------
Проблема возникла в новой схеме создания `moch`, которые содержат по одному тесту. Там слегка конфликтует логика удаления тестов при `silent` skip-e и логика удаления тестов в `attachTestsFilter`.
Идея фикса заключается в том, чтобы при `silent` skip-е ничего не удалять, а разруливать этот тип skip-ов на уровне `proxy-reporter`-а; кажется, что он прям для этого идеально подходит.
> fix: 'hermione.only.in' functionality

- README.md
Hi there,
love you're doing here, thanks! :)
Found that example in quick start section doesn't work. Actually there's a couple of problems here:
- `.search2__input input -> .search2__input .input__control` (there're two inputs actually, so webdriver fails on trying to pick up the right one)
```
✘ Error: invalid element state: Element is not currently interactable and may not be manipulated
```
- `waitForVisible` (the page needs some time after search request)
- `z-entity-card__title` doesn't seem exist anymore
- changed `com -> ru` to make sure the language is always the same (com can redirect to ru)
**UPD**
Changed test: goes to github page of hermione and find the title
> Fix for example in quick start section in Readme

- lib/hermione.js
- test/lib/hermione.js
Необходимо для того, чтобы можно было переопределить какие-то методы у hermione до того как они начнут использоваться. Например обернуть `emitAndWait`
> fix: load plugins early

- lib/browser.js
- lib/worker/browser-pool.js
- lib/worker/runner/mocha-runner/mocha-adapter.js
- test/lib/browser.js
- test/lib/worker/browser-pool.js
- do not call `config.prepareBrowser` in master process
- call `config.prepareBrowser` in browser pool after Browser intialization instead of calling it in Browser constructor
- wrap `config.prepareBrowser` call (and NEW_BROWSER event emitting) with `try-catch` block
> Fix: do not hang on errors in config.prepareBrowser

- .travis.yml
- package.json
BREAKING CHANGE: support only node>=6.4.0
> feat(node-support): drop of support node below 6.4.0

- README.md
- lib/base-hermione.js
- lib/constants/runner-events.js
- lib/hermione.js
- lib/worker/hermione.js
- lib/worker/index.js
- test/lib/cli/index.js
- test/lib/hermione.js
- test/lib/worker/hermione.js
- унес подключение плагинов в конструктор `hermione`
- добавил асинхронное событие `INIT`
- переименовал в `readTests` опцию `loadPlugins` в `silent`, т.к. плагины подключаются в конструкторе, просто при выставленной опции `silent` не летят события от раннера
> feat: load plugins synchronously in constructor, add async INIT event

- lib/cli/index.js
- lib/config/index.js
- lib/constants/runner-events.js
- lib/hermione.js
- test/lib/cli/index.js
- test/lib/config/index.js
- test/lib/hermione.js
- основная часть отсюда: https://github.com/gemini-testing/gemini/pull/852
- дополнительно:
- унес дефолтный путь к конфигу из cli собственно в `Config`
- немного причесал тесты на `cli`
> feat: allow to extend cli parser via CLI event

- README.md
- lib/runner/mocha-runner/retry-mocha-runner.js
- test/lib/runner/mocha-runner/retry-mocha-runner.js
Config should provide to users option to set custom rule whether test retry
needed or not. 
Relates to: 
* FEI-8660
* https://github.com/gemini-testing/retry-limiter/pull/6
> feat(config): introduce shouldRerty config option

- lib/browser/new-browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser/new-browser.js
sessionRequestTimeout, sessionQuitTimeout and screenshotOnRejectTimeout
for now by default equals to 90000
> fix: optional timeouts by default does not equal to httpTimeout

- lib/cli/index.js
- package-lock.json
- package.json
- test/lib/cli/index.js
/cc @j0tunn @sipayRT @DudaGod @eGavr
> feat: wrap tests running in command

- test/lib/reporter/plain.js
Один из 4-х пул риквестов в рамках одной задачи – покрыть гермиону тестами. Конечный результат в картинках, соответственно, представлен по 4-м пул риквестам.
Этот отвечает за покрытие `plain reporter`.
__В целом до__
__В целом после__
> Test-cover: plain reporter

- lib/signal-handler.js
- test/lib/hermione.js
- test/lib/signal-handler.js
Один из 4-х пул риквестов в рамках одной задачи – покрыть гермиону тестами. Конечный результат в картинках, соответственно, представлен по 4-м пул риквестам.
Этот отвечает за покрытие корневых файлов каталога `lib`.
__До__
__После__
__В целом до__
__В целом после__
> Test-cover lib/

- test/lib/worker/runner/index.js
- test/lib/worker/runner/mocha-adapter.js
Один из 4-х пул риквестов в рамках одной задачи – покрыть гермиону тестами. Конечный результат в картинках, соответственно, представлен по 4-м пул риквестам.
Этот отвечает за покрытие файлов каталога `lib/worker/runner`.
__До__
__После__
__В целом до__
__В целом после__
> Test-cover: worker/runner

- README.md
- lib/config/browser-config.js
- lib/config/browser-options.js
- lib/config/defaults.js
- lib/config/index.js
- test/lib/config/browser-config.js
- test/lib/config/options.js
Патч для https://github.com/gemini-testing/hermione/issues/246
* Из конфига теперь считывается свойство shouldRetry
* Добавлены тесты на shouldRetry
* Изменен конструктор BrowserConfig и поправлены тесты.
* Поправлено README.md
> fix: config property "shouldRetry" now works correctly

- lib/test-collection.js
- test/lib/test-collection.js
Инстанс TestCollection имитирует структуру `{browserId: rootSuite}`, которую возвращал ранее метод `hermione.readTests`
> fix: add backwards compatibility for hermione.readTests

- lib/test-reader/index.js
- test/lib/test-reader/index.js
`.only` на самом деле выставляет grep.
В итоге логика была такая:
- парсим тесты для первого браузера, там нет .only - грепа нет
- применяем греп для дерева первого браузера, его нет, читаем все тесты
- парсим тесты для второго, там .only - он записывается в греп
- применяем греп для дерева второго браузера, но первое дерево уже распаршено
Теперь сначала создаем все парсеры, потом всем парсерам выставляем grep, затем парсим все деревья, затем для всех деревьев применяем grep
> fix: .only does not work for all browsers

- lib/worker/runner/test-runner/index.js
- package-lock.json
- test/lib/worker/runner/test-runner/index.js
Контекст:
- объект `test` создается один раз при чтении тестов, затем кэшируется.
Для того, чтобы во время запуска тестов не модифицировался оригинальный объект `test` в `TestRunner`'е создается объект `_test`, которому в прототип записывается `test`
- во время выполнения хуков и тестов создается новый объект `hermioneCtx`, который доступен через `session.executionContext.hermioneCtx`, и который является клном оригинального `test.hermioneCtx`
Проблема: если доступ к `hermioneCtx` осуществляется через `session.executionContext.ctx.currentTest.hermioneCtx`, то модифицируется оригинальный `test.hermioneCtx`, в итоге:
- тесты не падают с ошибками `assertView`, т.к. модифицируется оригинальный `test.hermioneCtx`,  а проверяется склонированный
- результаты `assertView` записываются в …
> Avoid hermioneCtx sharing between different test runs

- README.md
- lib/base-hermione.js
- lib/constants/runner-events.js
- lib/hermione.js
- lib/runner/index.js
- test/lib/hermione.js
- test/lib/runner/index.js
Предполагается следующее API (сразу привожу пример как это будет использоваться в наших целях):
```js
module.exports = (hermione) => {
hermione.intercept(hermione.events.TEST_FAIL, ({event, data}) => {
if (/* muted test */) {
data.pending = true;
data.skipReason = 'failed muted test';
return {event: hermione.events.TEST_PENDING, data};
}
});
};
```
> feat: implement events interceptor API for plugins

- lib/browser/commands/assert-view/capture-processors/assert-refs.js
- lib/browser/commands/assert-view/capture-processors/update-refs.js
- lib/browser/commands/assert-view/errors/base-state-error.js
- lib/browser/commands/assert-view/errors/image-diff-error.js
- lib/browser/commands/assert-view/errors/no-ref-image-error.js
- lib/browser/commands/assert-view/index.js
- lib/worker/runner/test-runner/one-time-screenshooter.js
- test/lib/browser/commands/assert-view/errors/image-diff-error.js
- test/lib/browser/commands/assert-view/errors/no-ref-image-error.js
- test/lib/browser/commands/assert-view/index.js
- test/lib/worker/runner/test-runner/one-time-screenshooter.js
Эти размеры нужны для более правильно работы ленивой подзагрузки изображений в html-reporter. Для компоненты `react-lazyload` будем выставлять `height` изображения, при этом на страницу будет подставляться плейсхолдер таких же размеров пока картинка не загрузилась. С помощью данного плейсхолдера пропадет баг с постоянно дергающемся экраном когда скроллишь страницу.
Дока про `height` в react-lazyload - https://github.com/jasonslyvia/react-lazyload/tree/master/#height
> feat: add image sizes to assertViewResults

- lib/runner/test-runner/regular-test-runner.js
- test/lib/runner/test-runner/regular-test-runner.js
Проблема заключается в том , что если, например, на событие `AFTER_TESTS_READ` записать каждому тесту что-то в meta, то на события `TEST_PASS`, `TEST_FAIL` и т. д. этой информации в meta уже не будет.
> fix: test meta from worker totally redefines test meta from master

- lib/test-reader/mocha-test-parser.js
- test/lib/test-reader/mocha-test-parser.js
**Problem.**
We expect `npx hermione --grep="(foo|bar)"` to run both `foo` и `bar` tests, but instead none of them is run because special symbols are escaped: `/\(foo\|bar\)/ `.
**Solution.**
Pass already prepared `RegExp` object so that escaping doesn't occur.
> fix: stop escaping of special symbols in grep

- lib/test-reader/mocha-test-parser.js
- test/lib/test-reader/mocha-test-parser.js
Fix for the issue https://nda.ya.ru/3UXMrt
If `--grep` option is used, `pre-require` is triggered for all files in the set. Yet `suite.id()` is computed only when it is called.
Thus, `suite.id()` will return `id` derived from the last file in the set.
> fix: suite.id() no longer depends on parsing order

- README.md
Сейчас все ссылки с hermione ведут на оригинальный портал webdriver.io, но там api новой версии (v5) , и использовать её для разработки невозможно. 
Хорошо хотя бы ссылки бы обновить на верные, если нельзя отказаться от форка.
> docs(readme): link to correct wdio version

- README.md
- lib/browser/commands/assert-view/assert-view-results.js
- lib/browser/commands/assert-view/errors/assert-view-error.js
- lib/browser/commands/assert-view/index.js
- test/lib/browser/commands/assert-view/assert-view-results.js
- test/lib/browser/commands/assert-view/errors/assert-view-error.js
- test/lib/browser/commands/assert-view/index.js
BREAKING CHANGE: test with duplicate state names in 'assertView' calls will fail with 'AssertViewError'
> fix: forbid duplicate state names in 'assertView' within one test

- lib/runner/index.js
- test/lib/runner/index.js
BREAKING CHANGE: 'END' event handler will not recieve tests' statistic as the first argument
> feat: do not pass tests' statistic on 'END' event

- lib/test-collection.js
- test/lib/test-collection.js
`_.zip([], [])` returns empty array which leads to undefined values on subsequent unzipping.
> Fix: do not sort empty TestCollection

- lib/browser/commands/assert-view/capture-processors/assert-refs.js
- lib/browser/commands/assert-view/index.js
- test/lib/browser/commands/assert-view/capture-processors/assert-refs.js
- test/lib/browser/commands/assert-view/index.js
- test/lib/browser/utils.js
Do not ignore caret if none of the editable elements are in focus
> fix: logic of ignore caret option on ImageDiffError

- lib/test-reader/mocha-test-parser.js
- test/lib/test-reader/mocha-test-parser.js
Пока оставил для обратной совместимости `id` как функцию. В следующем мажоре выпилим
> fix: make test.id looks like a property

- lib/runner/test-runner/regular-test-runner.js
- test/lib/runner/test-runner/regular-test-runner.js
Fallback to force free browser if there was no freeBrowser event from worker
> fix: always release browser

- package-lock.json
- package.json
In version `4.16.1` of `@gemini-testing/webdriverio` we have extended `ESOCKETTIMEDOUT` messages: with browser commands and their arguments added to the messages.
> chore: up webdriverio version

- lib/runner/test-runner/regular-test-runner.js
- lib/worker/runner/test-runner/index.js
- test/lib/runner/test-runner/regular-test-runner.js
- test/lib/worker/runner/test-runner/index.js
При параллельном запуске одного и того же теста с использованием API метода `addTestToRun` возникает проблема с тем, что каждый тест содержит одинаковый id. И как только первый тест завершается, воркер эмитит событие `worker.TEST_ID.freeBrowser`. Это событие ловит мастер и отпускает все браузеры тестов, которые уже успели подписаться на это событие.
Необходимо для каждого запуска теста генерить уникальный `testRunId`. Решил реализовать это внутри `browserRunner` и строить id с использованием `browser.id` + счетчика тестов. После чего прокидываю этот уникальный id до `regularTestRunner`-а. А так же прокидываю его в воркер, который и эмитит освобождение браузера после завершения теста.
Другой вариант у меня был с помощью `Object.defineProperty` выставлять `runId` у теста, чтобы его можно …
> fix: use sessionId in freeBrowser event between master and worker

- lib/worker/runner/browser-pool.js
- lib/worker/runner/test-runner/index.js
- test/lib/worker/runner/browser-pool.js
- test/lib/worker/runner/test-runner/index.js
При падении подготовки браузера в воркерах летит ошибка мимо логики про `patternsOnReject`. Ошибка про `Session timed out or not found` является именно такой ошибкой, которая, как правило, воспроизводится при подготовке браузера для теста (выставление ориентации или размера экрана). Соответственно, проблема заключается в том, что мы в сессии, от которой уже один раз получили `Session timed out or not found` продолжаем запускать тесты (по количеству выставленных `testsPerSession`), а все тесты в этой сессии падают.
При любой ошибке в подготовке браузера помечаем сессию как `broken` и больше не запускаем в ней тесты.
> fix: never use browser session again if it fails on initializition

- README.md
- lib/browser/commands/assert-view/capture-processors/assert-refs.js
- lib/browser/commands/assert-view/index.js
- lib/config/browser-options.js
- lib/config/defaults.js
- package-lock.json
- package.json
- test/lib/browser/commands/assert-view/capture-processors/assert-refs.js
- test/lib/browser/commands/assert-view/index.js
- test/lib/config/browser-options.js
- test/lib/config/options.js
- в команде `assertView` теперь можно установить опцию:
- `compositeImage` - с помощью которой, можно точечно управлять снятием всего элемента или только видимой части;
- `captureElementFromTop` - с помощью которой, можно указать, что элемент должен быть снят с самого начала или с текущей позиции;
- `antialiasingTolerance` - раньше можно было устанавливать только `tolerance`.
- добавил опцию `assertViewOpts` на уровне браузера с помощью, которой можно установить опции используемые в каждой команде `assertView` по умолчанию, если они явно не заданы. При явном указании одной из опций внутри `assertView` она переопределит опцию из `assertViewOpts`.
- поправил создание диффа, раньше она брала значения `tolerance` и `antialiasingTolerance` из конфига, даже если значения были явно заданы через …
> feat: add ability to screen only visible part of the element in the viewport

- README.md
- lib/config/browser-options.js
- lib/config/defaults.js
- lib/worker/runner/test-runner/execution-thread.js
- test/lib/browser/existing-browser.js
- test/lib/config/browser-options.js
- test/lib/worker/runner/test-runner/execution-thread.js
Add command history to error if timeout is expired after running tests.
> feat: add command history to error for timedout tests

- README.md
- lib/cli/index.js
- test/lib/cli/index.js
- add new cli option `--require` to load external modules
- ~~break backward compatibility in order to be able to use short option `-r` for `--require` and not for `--reporter`. This is done because in node, mocha, webpack, ... this short option used exactly for require other modules.~~
> feat: add cli option "--require" to load external modules

- README.md
- lib/browser/commands/orientation/index.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser/commands/orientation/index.js
- test/lib/browser/utils.js
- test/lib/config/browser-options.js
- this option allows to disable wait until the orientation changes;
- currently it is necessary for ios safari;
> feat: add browser option "waitOrientationChange"

- README.md
While the function syntax for `screenshotsDir` is documented, a code example would be nice for discoverability. 
This prevent recurring questions like #442 (asked again today in the self-support Telegram chat).
> chore: add screenshotsDir function example

- lib/test-reader/browser/commands/version.js
- test/lib/test-reader/browser/commands/version.js
Added property for a test to be able to determine if a browser version of the test was overwritten from the native helper `browser().version()`.
> feat: added 'hasBrowserVersionOverwriten' property for test

- package-lock.json
- package.json
Up gemini-core@6.1.2 in which was looks-same updated to 7.3.0 in which add ability to compare images by buffers before parse them.
> chore: update gemini-core@6.1.2

- lib/worker/runner/test-runner/one-time-screenshooter.js
- test/lib/worker/runner/test-runner/one-time-screenshooter.js
The example with hermione-test which hangs on execution:
```
it('test1', async function() {
this.browser.addCommand('screenshot', () => {
return new Promise((resolve, reject) => {
console.log('BEFORE REJECT1!!!');
reject(`some error!!!`);
});
}, true);
await this.browser.foo();
});
```
This test will try to take screenshot on reject because `foo` method does not exists in `browser` but it will hangs forever because wdio@4 has custom promises implementation which does not work in that case correctly.
To fix this problem add timeout for execution screenshot on reject. Moreover this problem does not reproduce with wdio@6.
> fix: set timeout for execution screenshot on reject

- README.md
- lib/browser/existing-browser.js
- lib/config/browser-options.js
- lib/config/defaults.js
- test/lib/browser/existing-browser.js
- test/lib/config/browser-options.js
- typings/index.d.ts
This PR introduces new config option - `urlHttpTimeout` which is used as http timeout for requests to Selenium server while executing the `url` command. Might be helpful when `/url` requests are slow and require an increased timeout, but one doesn't want to affect anything else.
> Introducing the urlHttpTimeout config option

- package-lock.json
- package.json
- typings/index.d.ts
- typings/webdriverio/index.d.ts
- remove deprecated typings from `@types/webdriverio`
- use new typings from webdriverio
- use new typings from `@wdio/types`
proofs that it works:
- one
- two
> fix: use new typings from webdriverio

- README.md
- lib/config/browser-options.js
- package-lock.json
- package.json
- test/lib/config/browser-options.js
This PR sets `screenshotMode` to `'viewport'` for android browsers. These changes aim to get around the [chromium bug](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2853) due to which screenshots turn out larger than the visible viewport and have blank space at the bottom.
> fix: set correct screenshotMode for android browsers

- lib/browser/browser.js
- test/lib/browser/existing-browser.js
wdio при подключении к сессии с использованием CDP пытается понять нужно ли подключится к локальному браузеру или куда-то удаленно. Для того, чтобы это понять он смотрит на запрашиваемые пользователем капабилити. В случае если присутствует `selenoid:options`, то он понимает, что нужно подключится по урлу вида - `ws://${host}:4444/devtools/${browser.sessionId}`. Происходит это тут - https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/getPuppeteer.ts#L71-L79.
> fix(attach): pass "requestedCapabilities" in order to using CDP in CI

- typings/index.d.ts
Проблема:
При использовании `unknown` TS будет ругаться если в `ctx` положить функцию-хелпер
Пример:
`ctx: {
login: loginFunction
}`
В качестве решения - использовать `any`
> fix: use 'any' instead of 'unknown' typing for ctx

- lib/test-reader/mocha-test-parser.js
- test/lib/_mocha/suite.js
- test/lib/test-reader/mocha-test-parser.js
После переезда на новую моку перестала работать фильтрация сьютов с использованеием `.only`. Перестала она работать из-за того, что в моке эта логика уехала в [раннер](https://github.com/gemini-testing/mocha/blob/master/lib/runner.js#L1066), а этот раннер гермиона не использует. 
Поэтому после чтения тестов нужно явно вызвать у корневого сьюта метод, который фильтрует тесты.
> fix: correct logic for running it.only/describe.only

- README.md
- lib/worker/runner/test-runner/execution-thread.js
- test/lib/worker/runner/test-runner/execution-thread.js
```js
it('some test', async function() {
await this.browser.url('foo/bar');
});
```
=>
```js
it('some test', async ({ browser }) => {
await browser.url('foo/bar');
});
```
> Feat: pass browser into test as an argument

- README.md
- lib/test-reader/test-parser-api.js
- test/lib/test-reader/test-parser-api.js
Reverting https://github.com/gemini-testing/hermione/pull/495
Внесенная там функциональность никогда не работала корректно: на нижнем уровне парсер, от которого, пробрасываются события, создается один раз перед чтением **всех файлов** для конкретного браузера, и соответственно через [testParserApi](https://github.com/gemini-testing/hermione#test-parser-api) будут лететь события о всех тестах/хуках из всех файлов. При этом сам объект летит на событие `BEFORE_FILE_READ`, т.е. стоит подписаться в обработчике этого события, и для каждого файла будут лететь события о тестах/хуках из всех файлов.
И судя по тому, что за 2 года не было ни одного обращения про этот баг, то никто этим и не пользуется.
Предлагаю откатить функциональность здесь и ее использование в …
> fix: do not passthrough parser events via TestParserApi

- lib/browser/history/index.js
- test/lib/browser/history/index.js
- test/lib/browser/utils.js
when `saveHistory` enabled, `this` in commands, added via addCommand, pointed to browser even with `elementScope=true` flag
```
it('...', async ({browser}) => {
browser.addCommand('foobar', async function() {
console.log('this:', this); // browser instance, must be an element instance
}, true);
});
```
> fix: 'this' pointer in custom commands

- lib/browser/commands/assert-view/index.js
- test/lib/browser/commands/assert-view/index.js
- test/lib/browser/utils.js
Adds the ability to call element's assertView method like this:
```
it('element example', async ({browser}) => {
await browser.url('https://npmjs.com');
const elem = await browser.$('#main');
await elem.assertView('plain', {}); // state and options only
});
```
> feat: add element's assertView method

- lib/test-reader/index.js
- lib/test-reader/mocha-test-parser.js
- lib/worker/runner/caching-test-parser.js
- lib/worker/runner/index.js
- lib/worker/runner/test-runner/index.js
- test/lib/_mocha/index.js
- test/lib/test-reader/index.js
- test/lib/test-reader/mocha-test-parser.js
- test/lib/worker/runner/caching-test-parser.js
- test/lib/worker/runner/index.js
2 ключевых момента:
- для одного браузера тестовые файлы грузятся асинхронно
- для разных браузеров пачки тестов грузятся последовательно. В этом отличие от https://github.com/gemini-testing/hermione/pull/612, и без этого парсинг для нескольких браузеров корректно не пройдет - внутри файлов с тестами активно используется global (и нами и mocha), будут конфликты
**Важно**: ESM-модули пока корректно работать не будут, т.к. там другая система кэширования. Это буду чинить отдельно
> feat: load test files asynchronously

- lib/worker/runner/test-runner/one-time-screenshooter.js
- test/lib/worker/runner/test-runner/one-time-screenshooter.js
Осталось после https://github.com/gemini-testing/hermione/pull/663
`png-img` просто не умел сохранять в `base64`, поэтому мы сохраняли во временный файл, а потом просто читали этот файл через `fs` и конвертировали в `base64`.
После перехода на `sharp` этот костыль стал бесполезен
> chore: remove redundant code for saving useless image

- README.md
- lib/config/defaults.js
- lib/config/options.js
- lib/test-reader/index.js
- lib/test-reader/mocha-test-parser.js
- lib/worker/runner/simple-test-parser.js
- package-lock.json
- package.json
- test/lib/config/options.js
- test/lib/test-reader/index.js
- test/lib/test-reader/mocha-test-parser.js
- test/lib/worker/runner/simple-test-parser.js
- test/utils.js
- typings/index.d.ts
- typings/webdriverio/index.d.ts
Добавил библиотеку expect-webdriverio - https://github.com/webdriverio/expect-webdriverio/tree/v3. Использовал именно 3 версию, так как 4 сейчас находится в бете и в ней они переходят на esm модули.  API по использованию находится тут - https://webdriver.io/docs/api/expect-webdriverio/.
Тестировал на тестовом проекте.
> feat: add built-in assert library

- .github/workflows/node.js.yml
- .travis.yml
- package.json
BREAKING CHANGE: node versions less than 14.0.0 are no longer supported
> feat: drop node versions less than 14

- typings/index.d.ts
`TestResult` contains `err` field, but it doesn't have `screenshot` field inside, but it exists.
> fix: add err field to test result

- README.md
- lib/runner/test-runner/regular-test-runner.js
- lib/runner/test-runner/skipped-test-runner.js
- lib/test-collection.js
- lib/test-reader/test-object/configurable-test-object.js
- lib/test-reader/test-object/hook.js
- lib/test-reader/test-object/test-object.js
- lib/test-reader/test-object/test.js
- lib/worker/runner/test-runner/hook-runner.js
- lib/worker/runner/test-runner/index.js
- test/lib/runner/test-runner/index.js
- test/lib/runner/test-runner/insistant-test-runner.js
- test/lib/runner/test-runner/regular-test-runner.js
- test/lib/runner/test-runner/skipped-test-runner.js
- test/lib/test-collection.js
- test/lib/test-reader/test-object/configurable-test-object.js
- test/lib/test-reader/test-object/hook.js
- test/lib/test-reader/test-object/test-object.js
- test/lib/test-reader/test-object/test.js
Inheritance through `Object.create` doesn't work wery well with inheritance through `extends`
> fix: use test.clone instead of Object.create(test) to avoid test modification

- lib/test-reader/test-object/configurable-test-object.js
- test/lib/test-reader/test-object/configurable-test-object.js
html-reporter gui expects `undefined` for `browserVersion` property
> fix: use undefined as a default value for browserVersion and browserId properties

- src/test-reader/browser-test-parser.js
- test/lib/test-reader/browser-test-parser.js
- test/utils.js
Browser system sections just duplicates common system section
> chore: browser-test-parser: get system options from common config section

- src/worker/runner/simple-test-parser.js
- test/lib/worker/runner/simple-test-parser.js
Fix after https://github.com/gemini-testing/hermione/pull/734 and https://github.com/gemini-testing/hermione/pull/736
> fix: call BrowserTestParser methods correctly in workers

- package-lock.json
- package.json
- src/base-hermione.js
- src/config/defaults.js
- src/config/index.js
- src/utils/typescript.ts
- test/lib/config/browser-options.js
- test/lib/config/index.js
- test/lib/config/options.js
- test/lib/utils/typescript.ts
- test/types.ts
- Hermione теперь умеет читать конфиг и тесты на typescript
- Проведено исследование производительности
- Опробовано множество вариантов, финальный – использование `ts-node` с возможностью ускорения путем установки `@swc/core`
- `ts-node` сделал optional peerDependency, так делает, например, jest
- `@swc/core` вообще нигде не фигурирует в зависимостях, просто подхватится автоматически, если пользователь установит. Планирую отразить это в доке, буду обновлять доку после последнего чанка интеграции с TS – правок тайпингов
- Проверка типов при запуске тестов не производится
- По умолчанию пни чтении вообще не используется tsconfig проекта – в целом, при отсутствии проверки типов конфигурация особо не нужна (на что-то влияет только target и module). Но при желании с помощью переменных …
> feat: support tests and config on typescript

- src/browser/camera/index.js
- src/browser/camera/utils.js
- src/browser/client-scripts/index.js
- src/browser/client-scripts/rect.js
- src/browser/client-scripts/util.js
- src/browser/screen-shooter/index.js
- src/browser/screen-shooter/viewport/index.js
- test/src/browser/camera/index.js
- test/src/browser/screen-shooter/viewport/index.js
Реализовал поддержку девайсов с дробным `pixelRatio`. Основная проблема была с `getBoundingClientRect`, который при дробном `pixelRatio` может вернуть ширину например со значением - `393.0909118652344`. А дальше мы это значение всегда `ceil`-им, чтобы отображать целый пиксель. Но обычно и `clientWidth` был равен этому округленному значению. А с дробными `pixelRatio` может быть такое, что `clientWidth = 393`, а от `getBoundingClientRect` `width = 394` (т.е. после округления). В итоге снимаемая область вываливалась за размер вьюпорта и кидали ошибку.
Теперь такой проблемы не будет.
> fix: correctly screen elements on device with fractional pixel ratio

- src/worker/runner/test-runner/index.js
- test/src/worker/runner/test-runner/index.js
**Что сделано**
* исправляю ошибку при сбросе курсора в нулевую позицию, которая возникает в том случае, если у `body` после подскролла оказываются отрицательные координаты
> fix: reset cursor correctly for body with negative coords

- package-lock.json
- package.json
- src/utils/processor.js
Внутри wdio используется got для http запросов. При выполнении запросов через got wdio устанавливает http и https агенты и таймаут на запрос. В итоге в случае если за отведенный таймаут запрос не был выполнен, то got кидает ошибку в которой содержатся циклические ссылки из-за использования своих агентов. После чего из worker-а пытаемся прокинуть ошибку в мастер с помощью `process.send` и под капотом выполняется `JSON.stringify` и в итоге получаем `Unhandled rejection` так как обработки ошибки не хватило.
Использовать библиотеку `serialize-error` с помощью которой можно удалить циклические ссылки.
> fix: handle unhandled rejections with circular refs on timeout error

- src/browser/browser.js
- src/browser/new-browser.js
- test/src/browser/new-browser.js
- typings/index.d.ts
Флаги взяты отсюда: https://webdriver.io/docs/capabilities/#run-browser-headless
У меня есть пара вопросов:
- я не вижу в коде гермионы нигде упомянания конкретных браузеров. Я правильно понимаю, что `desiredCapabilities.browserName` (который по докам является User Agent, и по логике может быть arbitary) и есть идентификатор конкретного движка? 
Я вообще ожидал что где-то в коде будет список поддерживаемых браузеров, и я не буду хардкодить "chrome", "msedge" и тп. Может быть я что-то пропустил.
- почему в доках гермионы есть `headless` настройка уже 2 года, а по сути ее не было все это время?)
- как осуществлять е2е тестирование? не вижу чтобы у нас были е2е тесты в репо. Как мне удостоверится что оно реально работает, а не только в юнит тестах? CI у нас как-то сделан помимо юнит тестов в …
> feat: add "headless" setting for the main 3 browsers

- src/browser/browser.js
- src/browser/existing-browser.js
- src/worker/runner/browser-pool.js
- test/src/browser/existing-browser.js
- test/src/browser/new-browser.js
- test/src/worker/runner/browser-pool.js
Stop using cache of browsers sessions in worker. Causes:
- selenium/selenoid/... return `se:cdp` capability in response with `sessionId` on the end of the url and we don't modify it; 
- if use cdp protocol to quickly open browsers (in the near future), then we need reinitialize additional options in cached browsers;
- no big difference in execution speed, but a lot of problem with support in future.
> fix: do not reinit cached browser session in worker

- package-lock.json
- package.json
- src/base-hermione.ts
- src/browser/new-browser.js
- test/src/browser/new-browser.js
- test/src/hermione.js
Починил `system.debug` в конфиге
Установил дефолтное значение `LOG_LEVEL` на `"error"`
> fix: system.debug config field

- package-lock.json
- package.json
- src/browser/commands/assert-view/capture-processors/assert-refs.js
- src/browser/commands/assert-view/errors/image-diff-error.ts
- src/browser/commands/assert-view/index.js
- src/image.js
- test/src/browser/commands/assert-view/index.js
- test/src/image.js
- Обновил `looks-same`
- Прокинул `diffBuffer`
> perf: provide diffBuffer in ImageDiffError

- typings/index.d.ts
Typings are out of sync as of now: in code, id is a property, however in types it's still a method. This PR addresses this issue.
> fix: fix test id to be property and not a method in typings

- src/index.ts
- src/types/index.ts
- Added exports of `TestResult` and `Suite` types
- Impoved `AssertViewResult` types
- These types are needed in https://github.com/gemini-testing/html-reporter/pull/493
> fix: export TestResult and Suite types

- package-lock.json
- package.json
- src/browser/commands/assert-view/capture-processors/assert-refs.js
- src/browser/commands/assert-view/errors/image-diff-error.js
- src/browser/commands/assert-view/index.js
- src/image.js
- test/src/browser/commands/assert-view/index.js
- test/src/image.js
Бэкпорт PR https://github.com/gemini-testing/hermione/pull/781 на v7
> perf: provide diffBuffer in ImageDiffError (backport to v7)

- package-lock.json
- package.json
- src/browser/commands/index.js
- src/browser/commands/openAndWait.ts
- src/config/browser-options.js
- src/config/defaults.js
- src/utils/page-loader.ts
- test/src/browser/commands/openAndWait.ts
- test/src/browser/utils.js
- test/src/utils/page-loader.ts
Добавил метод `openAndWait`:
- Открыть страницу
- Подождать появления селекторов
- Подождать предикат
- Подождать неактивности сети
- Кинуть ошибку при ошибке загрузки ресурса
> feat: wait page load

- README.md
Fixes:
- https://github.com/gemini-testing/hermione/issues/453
- https://github.com/gemini-testing/hermione/issues/630
> docs: fix programmatic api section

- README.md
- src/browser/client-scripts/index.js
- src/browser/client-scripts/util.js
- src/browser/commands/assert-view/index.js
- src/browser/commands/types.ts
- src/browser/existing-browser.js
- src/config/browser-options.js
- src/config/defaults.js
- test/src/browser/existing-browser.js
- test/src/browser/utils.js
Добавил возможность отключать анимации при вызове `assertView`
> feat: add ability to disable animations in assertView

- README.md
- package-lock.json
- package.json
- src/browser/existing-browser.js
- src/config/browser-options.js
- src/config/defaults.js
- src/config/utils.js
- test/src/browser/existing-browser.js
- test/src/browser/new-browser.js
- test/src/browser/utils.js
- test/src/config/browser-options.js
BREAKING CHANGE: "headers" in the config are now an object with a "X-Request-ID" by default
> feat: generate "X-Request-ID" header

- src/browser/existing-browser.js
- test/src/browser/existing-browser.js
- test/src/browser/utils.js
Method `switchToParentFrame` is not supported in ios, so I used `switchToFrame(null)` which does the same thing.
> fix: correctly disable animations in iframes for ios

- README.md
- src/browser-pool/basic-pool.js
- src/browser/browser.js
- src/browser/existing-browser.js
- src/browser/new-browser.js
- src/constants/browser.ts
- src/runner/browser-agent.js
- src/runner/browser-runner.js
- src/runner/test-runner/high-priority-browser-agent.js
- src/runner/test-runner/regular-test-runner.js
- src/worker/runner/browser-agent.js
- src/worker/runner/browser-pool.js
- src/worker/runner/index.js
- src/worker/runner/test-runner/index.js
- test/src/browser-pool/basic-pool.js
- test/src/browser/existing-browser.js
- test/src/browser/new-browser.js
- test/src/browser/utils.js
- test/src/runner/browser-agent.js
- test/src/runner/browser-runner.js
- test/src/runner/test-runner/high-priority-browser-agent.js
- test/src/runner/test-runner/regular-test-runner.js
- test/src/worker/runner/browser-agent.js
- test/src/worker/runner/browser-pool.js
- test/src/worker/runner/index.js
- test/src/worker/runner/test-runner/index.js
> feat: generate "X-Request-ID" header for each browser request (backport to v7)

- src/browser/browser.js
- src/browser/existing-browser.js
- src/runner/test-runner/regular-test-runner.js
- src/worker/hermione.ts
- src/worker/runner/browser-agent.js
- src/worker/runner/browser-pool.js
- src/worker/runner/index.js
- src/worker/runner/test-runner/index.js
- test/src/browser/existing-browser.js
- test/src/browser/new-browser.js
- test/src/browser/utils.js
- test/src/runner/test-runner/regular-test-runner.js
- test/src/worker/runner/browser-agent.js
- test/src/worker/runner/browser-pool.js
- test/src/worker/runner/index.js
- test/src/worker/runner/test-runner/index.js
In previous PR - https://github.com/gemini-testing/hermione/pull/819 I did not take into account the case with the correct specification of `testXReqId` when using the same browser for several tests. The problem was that the browser was cached and its field `testXReqId` was not modified for next test.
> fix: correctly generate test x request id for each test in one browser

- src/browser/browser.js
- src/browser/existing-browser.js
- src/runner/test-runner/regular-test-runner.js
- src/worker/runner/browser-agent.js
- src/worker/runner/browser-pool.js
- src/worker/runner/index.js
- src/worker/runner/test-runner/index.js
- test/src/browser/existing-browser.js
- test/src/browser/new-browser.js
- test/src/browser/utils.js
- test/src/runner/test-runner/regular-test-runner.js
- test/src/worker/runner/browser-agent.js
- test/src/worker/runner/browser-pool.js
- test/src/worker/runner/index.js
- test/src/worker/runner/test-runner/index.js
backport from - https://github.com/gemini-testing/hermione/pull/825
> fix: correctly generate test x request id for each test in one browser (backport to v7)

- src/browser/new-browser.js
- src/cli/index.js
- src/hermione.ts
- test/src/browser/new-browser.js
- test/src/cli/index.js
- test/src/hermione.js
add ability to use devtools procotol through cli option `--devtools` in order to make it easier to switch between the two protocols (`devtools` and `webdriver`).
> feat: add ability to use devtools procotol through cli option

- src/browser-pool/limited-pool.js
- src/runner/test-runner/regular-test-runner.js
- test/src/browser-pool/limited-pool.js
Cherry pick from - https://github.com/gemini-testing/hermione/pull/836
> fix: do not lost "testXReqId" when using "parallelLimit"

- README.md
- src/browser/commands/index.js
- src/browser/commands/moveCursorTo.ts
- src/worker/runner/test-runner/index.js
- test/src/worker/runner/test-runner/index.js
Fix for - https://github.com/gemini-testing/hermione/issues/841
> fix: move cursor relative to the center of body when using "resetCursor" option

- package-lock.json
- package.json
```
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
```
> chore(npm): removed @types/chalk

- README.md
- src/browser/commands/assert-view/capture-processors/assert-refs.js
- src/browser/commands/assert-view/errors/image-diff-error.ts
- src/browser/commands/assert-view/index.js
- src/browser/commands/types.ts
- src/config/defaults.js
- test/src/browser/commands/assert-view/capture-processors/assert-refs.js
- test/src/browser/commands/assert-view/errors/image-diff-error.js
- test/src/browser/commands/assert-view/index.js
Implemented `ignoreDiffPixelCount` optional param to `assertView` command.
With there params, it would be possible to ignore 2-5 pixel image diffs, which are hard to get rid of
Example:
```ts
it('example', async ({browser}) => {
// ignores up to 5 diff pixels
await browser.assertView('some-state', 'some-selector', {ignoreDiffPixelCount: 5});
// ignores up to 5% diff pixels
await browser.assertView('other-state', 'other-selector', {ignoreDiffPixelCount: "5%"});
});
```
> feat: add ability to specify ignoreDiffPixelCount in assertView

- src/types/index.ts
- added missing typings for `differentPixels` and `diffRatio` fields
> fix: extend AssertViewResultDiff type

- src/browser/client-scripts/index.js
- src/browser/client-scripts/rect.js
- src/browser/client-scripts/util.js
`getBoundingClientRect` inside iframe returns DOMRect only inside this iframe and don't know nothing about offsets between this iframe and viewport. Therefore, a solution has been implemented that takes into account the indentation of the iframe
Fix issue - https://github.com/gemini-testing/hermione/issues/349
> fix: correctly screen elements inside iframes

- src/config/index.ts
- test/src/config/index.js
- add ability to use `export default` in `.hermione.conf.(j|t)s` file. At the moment `.ts` config has to be `export =`
> feat: add ability to use default export in .hermione.conf file

- src/utils/typescript.ts
- test/src/utils/typescript.ts
- Add ability to use "import" and "export" statements in tests
https://www.typescriptlang.org/tsconfig/#allowJs
> feat: add ability to use import and export in test files

- src/browser/types.ts
- Add `browser.getConfig` typings
> fix: add getConfig command typings

- README.md
- src/browser/new-browser.js
- src/config/browser-options.js
- src/config/types.ts
- test/src/browser/new-browser.js
- test/src/config/browser-options.js
> feat: add ability to enable new Chrome headless mode

- src/browser/browser.js
- src/browser/commands/assert-view/index.js
- src/browser/commands/clearSession.ts
- src/browser/commands/getConfig.js
- src/browser/commands/getPuppeteer.js
- src/browser/commands/moveCursorTo.ts
- src/browser/commands/openAndWait.ts
- src/browser/commands/runStep.js
- src/browser/commands/scrollIntoView.ts
- src/browser/commands/setOrientation.js
- src/browser/commands/switchToRepl.ts
- src/browser/existing-browser.js
- src/browser/types.ts
This PR adds missing types for `moveCursorTo` and `openAndWait` commands and changes command exports from `export =` to `export default`.
> fix: add missing command types (moveCursorTo and openAndWait)

- README.md
- package-lock.json
- package.json
- src/bundle/constants.ts
- src/bundle/index.ts
- src/bundle/test-transformer.ts
- src/config/defaults.js
- src/test-reader/test-parser.js
- src/test-reader/test-transformer.ts
- test/src/test-reader/test-parser.js
- test/src/test-reader/test-transformer.ts
- tsconfig.json
Added ability to read tests in `.jsx` and `.tsx` files. To do this, it was necessary to add a code transpiler - babel. Used in order to convert components like `<h1>foo</h1>` to code which can be required.
In this PR supports only commonjs because esm projects not working with Hermione at the moment.
> feat: ability to read tests in ".jsx" and ".tsx" files

- README.md
- src/types/index.ts
Resolves #883
- Extend interface `HermioneCtx` from module "hermione":
```ts
// global.d.ts
import type { HermioneCtx } from "hermione";
declare module "hermione" {
interface HermioneCtx {
someFunc(): void;
}
}
```
- Use `hermione.ctx` with extended typings:
```ts
hermione.ctx.someFunc // () => void
```
> feat: add ability to extend hermione.ctx typings

- src/browser/types.ts
- add absent `origCommand` parameter to OverwriteCommandFn
> fix: return origCommand type to overwriteCommand

- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- src/browser/commands/types.ts
- src/browser/types.ts
- src/config/types.ts
Only changed repository name, repository links, fixed README.md. No code was changed
> Github: refresh README

- src/index.ts
- Extend interface `GlobalHelper` from module "hermione":
```ts
// global.d.ts
import type { GlobalHelper } from "hermione";
declare module "hermione" {
interface GlobalHelper {
also: {
in: (args: string | string[]) => void;
};
}
}
```
- Use `hermione.also.in` with extended typings:
```ts
hermione.also.in('foo');
```
> feat: add ability to extend "hermione" global variable

- src/runner/browser-env/vite/browser-modules/constants.ts
- src/runner/browser-env/vite/browser-modules/driver.ts
- src/runner/browser-env/vite/browser-modules/expect.ts
- src/runner/browser-env/vite/browser-modules/index.ts
- src/runner/browser-env/vite/browser-modules/types.ts
- src/runner/browser-env/vite/plugins/generate-index-html.ts
- src/runner/browser-env/vite/server.ts
- src/runner/browser-env/vite/socket.ts
- src/runner/browser-env/vite/types.ts
- src/worker/browser-env/runner/test-runner/constants.ts
- src/worker/browser-env/runner/test-runner/index.ts
- test/src/worker/browser-env/runner/test-runner/index.ts
- typings/global.d.ts
Added the ability to use a `expect` instance on the client side when running component or unit tests.
> feat: add ability to use expect in component tests

- src/runner/browser-env/vite/browser-modules/constants.ts
- src/runner/browser-env/vite/browser-modules/mocha/index.ts
- src/runner/browser-env/vite/browser-modules/types.ts
- src/runner/browser-env/vite/browser-modules/utils/console.ts
- src/runner/browser-env/vite/browser-modules/utils/index.ts
- src/runner/browser-env/vite/socket.ts
- src/runner/browser-env/vite/types.ts
- src/worker/browser-env/runner/test-runner/index.ts
- test/src/worker/browser-env/runner/test-runner/index.ts
Added the ability to show user log in nodejs environment when tests run in browser environment
> feat: add ability to show user log in component tests

- .github/workflows/node.js.yml
- src/runner/browser-env/index.ts
- src/runner/browser-env/vite/browser-modules/globals.ts
- src/worker/browser-env/runner/test-runner/index.ts
- test/src/runner/browser-env/index.ts
- test/src/worker/browser-env/runner/test-runner/index.ts
If the user run browsers in the cloud, and the server is launched locally, then the user needs to launch some tunneler instance. In this case, the base url is usually substituted on tunneler url. Therefore, the worker must connect directly to the server (not use url from tunneler). And the browser should not explicitly specify the transport. Since the tunnel may not support a websocket connection.
> fix: correctly connect to vite server from clients (worker, browser)

- .github/workflows/node.js.yml
- README.md
- package-lock.json
- package.json
- src/config/defaults.js
- src/config/options.js
- src/config/types.ts
- src/dev-server/index.ts
- src/dev-server/utils.ts
- src/hermione.ts
- test/src/config/options.js
- test/src/dev-server/index.ts
- test/src/dev-server/utils.ts
Added ability to specify dev server in config file:
Example
```js
const SERVER_PORT = 3000;
...
module.exports = {
...
devServer: {
command: "npm run server:dev",
env: {PORT: SERVER_PORT},
readinessProbe: {
url: `http://localhost:${SERVER_PORT}/health`
}
}
}
```
Command could also be `node some/file.js` or something else
> feat: add ability to use dev server

- package-lock.json
- package.json
- src/browser/stacktrace/utils.ts
- src/error-snippets/constants.ts
- src/error-snippets/frames.ts
- src/error-snippets/index.ts
- src/error-snippets/source-maps.ts
- src/error-snippets/types.ts
- src/error-snippets/utils.ts
- src/reporters/flat.js
- src/reporters/utils/helpers.js
- src/worker/runner/test-runner/index.js
- test/src/error-snippets/frames.ts
- test/src/error-snippets/index.ts
- test/src/error-snippets/source-maps.ts
- test/src/error-snippets/utils.ts
Add error snippets
Notice how stacktrace says example.hermione.tsx?import:**12:18**, but we are pointing to line 18 because of source map evaluation
> feat: add error snippets

- src/bundle/test-transformer.ts
- src/test-reader/index.js
- src/test-reader/test-parser.js
- src/test-reader/test-transformer.ts
- src/worker/runner/simple-test-parser.js
- test/src/test-reader/test-parser.js
- test/src/test-reader/test-transformer.ts
Fixed removing extra imports in nodejs env.
> fix: dont remove imports in nodejs env

- src/browser/client-scripts/index.js
fix - https://github.com/gemini-testing/testplane/issues/779
> fix: correctly screen element after moveTo

- typings/api.d.ts
I made a mistake in this PR - https://github.com/gemini-testing/testplane/pull/933. Types should be imported from build folder, which is published in npm.
Fixes - https://github.com/gemini-testing/testplane/issues/940
> fix: types for describe, it

- package-lock.json
- package.json
- src/browser/commands/switchToRepl.ts
- src/errors.ts
- src/errors/abort-on-reconnect-error.ts
- src/errors/testplane-internal-error.ts
- src/runner/browser-env/vite/browser-modules/errors/index.ts
- src/runner/browser-env/vite/browser-modules/globals.ts
- src/runner/browser-env/vite/browser-modules/types.ts
- src/runner/browser-env/vite/socket.ts
- src/runner/browser-env/vite/types.ts
- src/worker/browser-env/runner/test-runner/constants.ts
- src/worker/browser-env/runner/test-runner/execution-thread.ts
- src/worker/browser-env/runner/test-runner/index.ts
- src/worker/runner/test-runner/execution-thread.js
- src/worker/runner/test-runner/index.js
- src/worker/runner/test-runner/types.ts
- test/src/browser/commands/switchToRepl.ts
- test/src/worker/browser-env/runner/test-runner/index.ts
- test/src/worker/runner/test-runner/execution-thread.js
Vite which is used inside component tests support hmr (hot module replacement) it means that it can reload page if something changed (for example if user modify test file). So in this PR I implement ability to rerun test runnables if vite reload page with test.
> feat(ct): support hot module replacement

- src/runner/browser-env/vite/browser-modules/utils/console.ts
- src/runner/browser-env/vite/server.ts
- src/runner/browser-env/vite/types.ts
The problem occurs when you try to log an html element in test which use browser runner. Because html element has cyclic links and test crashes on call `JSON.stringify` when transferring such an element between processes.
So I use `outerHTML` if it exists.
> fix(ct): do not fail on log html elements

- docs/migration-from-hermione.md
- src/test-reader/test-parser.js
Typings are already correct: https://github.com/gemini-testing/testplane/blob/1e797a6d257a85ef1954a256879ba8703e24a7f0/src/types/index.ts#L163-L168
> fix: pass extra field on file events to fix breaking change

- src/index.ts
- src/types/index.ts
After this PR, user would be able to use clean module augmentation. Example:
```ts
import type { TestFunctionCtx as TestplaneTestFunctionCtx } from "testplane";
declare module 'testplane' {
export interface TestFunctionCtx extends TestplaneTestFunctionCtx {
myFunc(var1: string, var2: number): Promise<void>;
}
}
```
Also he would be able to pass test function context to other functions and type them properly:
https://github.com/gemini-testing/testplane/discussions/939
> feat: export TestFunctionCtx type

- README.md
- docs/debugging.md
- src/browser/browser.js
- src/browser/existing-browser.js
- src/runner/test-runner/regular-test-runner.js
- test/src/runner/test-runner/regular-test-runner.js
A randomly generated traceparent header unique for each test is added to all requests.
> feat: add traceparent header to all requests

- docs/config.md
- docs/writing-tests.md
- src/config/browser-options.js
- src/config/defaults.js
- src/test-reader/build-instructions.js
- src/test-reader/controllers/also-controller.ts
- src/test-reader/test-object/configurable-test-object.ts
- src/test-reader/test-object/hook.ts
- src/test-reader/test-object/types.ts
- src/test-reader/test-parser.js
- src/types/index.ts
- test/src/config/browser-options.js
- test/src/test-reader/build-instructions.js
- test/src/test-reader/controllers/also-controller.ts
- test/src/test-reader/test-object/configurable-test-object.js
- test/src/test-reader/test-parser.js
- implement ability to specify browser as passive using option "passive: true" in browser config;
- make "browserId" as string for runnables, because I don't see case in which it can be `undefined`;
- add "enable" method for all runnables (use it inside `testplane.also.in`);
- add "also" controller in `global.testplane` in order to be able to run test in passive browser.
> feat: implement ability to specify browser as passive

- src/config/defaults.js
- look for configs in format testplane.config.{ts,js,cts,cjs}. Previously, we supported configs in the format `.testplane.conf.{ts,js}`.
> feat: look for configs in format testplane.config.{ts,js,cts,cjs}

- src/browser/stacktrace/index.ts
- src/browser/stacktrace/utils.ts
- src/error-snippets/frames.ts
- src/error-snippets/source-maps.ts
- src/error-snippets/utils.ts
- src/utils/fs.ts
- test/src/browser/stacktrace/index.ts
- test/src/browser/stacktrace/utils.ts
- test/src/error-snippets/utils.ts
Examples: https://nda.ya.ru/t/1XWaQ6YG76y5LA
> fix: support error snippets nested browser commands

- src/reporters/utils/helpers.js
- test/src/reporters/flat.js
- add information to log with test result about pid in which test was run.
It will look like this:
```shell
[13:39:22 +0300] ✓ test example [chrome:d049e4a3-903d-489b-8571-2ea8fd7da04b, pid:27200] - 963ms
```
> feat: add "pid" to log info with test result

- src/browser/client-scripts/index.js
Revert change from - https://github.com/gemini-testing/testplane/pull/928. The problem is that after this change, an error occurs under certain conditions: `Image to composite must have same dimensions or smaller`. I solved this error in this PR - https://github.com/gemini-testing/testplane/pull/992, but I can't merge it, because it leads to differences in screenshots (when viewport has fractional dimensions).
Because of this, I am rolling back the old change and we will implement it back in the next major - testplane@9.
> fix: revert round of viewport

- src/cli/index.js
- src/utils/processor.js
As `JSON.stringify` of `Error` is `{}`, it is not the best thing to use, as well as `String(Error)`, which does not include "stack"
`util.inspect` solves the problem.
> fix: use propper unhandled rejection error serialization

- package-lock.json
- package.json
In order to support all yarn versions. More info here - https://github.com/gemini-testing/plugins-loader/pull/14
> chore: update plugins-loader from 1.3.3 to 1.3.4

- src/runner/index.ts
- src/worker/index.js
- src/worker/testplane-facade.ts
- test/src/runner/index.js
- test/src/worker/index.js
- test/src/worker/testplane-facade.js
In the case when the user switches to REPL mode and then someone calls `halt` method, then Testplane does not end correctly. In this case, it is necessary to explicitly close the repl server in worker. So I did it.
> fix: stop REPL servers on call "halt" method

- src/bundle/test-transformer.ts
- src/utils/module.ts
- test/src/test-reader/test-transformer.ts
Some libraries can load css files when you import them in component test file. For example:
```
// test.testplane.tsx
import {Button} from "some-component-library";
describe("suite", {...});
```
This file executes not only in browser, but also in nodejs environment. Where I get an error like: `Unexpected token ...` when try to import it. To solve this problem we use pirates + babel, they remove unnecessary imports. But when user import some module (without file extension) we can't figure out if it needs to be ignored in node env or not.
So in order to fix this problem we first require this module and if we get `Unexpected token ...` error from css file then we remove it.
> fix(component-testing): correctly import components with css from third party libraries

- src/bundle/test-transformer.ts
- test/src/test-reader/test-transformer.ts
In component testing user can import esm modules in the test file, because it executes in the browser, which support them. But test files also import in nodejs environment which supports only cjs. Because of this all esm only modules throw `ERR_REQUIRE_ESM` error in nodejs env.
So i implement replacing import esm module to variable with proxy. Like this:
```
// From:
import esmPkg from "esm-module";
// To:
const esmPkg = new Proxy({}, {
get: function (target, prop) {
return prop in target ? target[prop] : new Proxy(() => {}, this);
},
apply: function () {
return new Proxy(() => {}, this);
}
});
```
This proxy gives ability to call every method or getter that user want.
Need review only second commit.
> fix(component-testing): ability to import esm modules

- docs/typescript.md
- src/browser/types.ts
- src/index.ts
- src/types/index.ts
In this PR, I add export of ExecutionThreadCtx, which lets users extend via declaration merging it as follows:
```typescript
declare module 'testplane' {
interface ExecutionThreadCtx {
customField: string;
}
}
```
> fix: expose ExecutionThreadCtx

- src/config/browser-options.js
- test/src/config/browser-options.js
The screenshotsDir field is not parsed correctly for browsers if the user uses the deprecated value (hermione/screens) and the field itself is specified at the top level (i.e. not inside any browser).
> fix: correctly define screenshotsDir option for browsers

- src/browser/history/index.ts
- src/browser/history/rrweb.ts
- Fixed snapshots not being recorded in firefox, because this in `eval()` was pointing to sandbox. In `window.eval()` it works fine.
- Added color scheme changes tracking, which allows us to record whether user has dark theme enabled or not.
> fix: fix firefox rrweb recordings and track color scheme changes

- .github/workflows/node.js.yml
- enable pkg.pr.new - https://github.com/stackblitz-labs/pkg.pr.new in order to trigger release in PR without publishing anything to npm
> chore(ci): setup pkg.pr.new

- src/config/browser-options.js
- src/constants/browser.ts
- test/src/config/browser-options.js
Chrome@127 and lower doesn't have feature that used inside webdriverio. So when you open url in that browser you got an error: `Navigation to 'https://webdriver.io' timed out as no request payload was received`. According to this error, it is not clear what the problem is. Therefore, when parsing the config, I throw an error if used chrome@127 and lower with BiDi protocol (specified `webSocketUrl: true` capability)
> fix: throw error if chrome not support bidi protocol

- package-lock.json
- package.json
- src/browser/commands/moveCursorTo.ts
- src/browser/commands/types.ts
- src/runner/browser-env/vite/browser-modules/expect.ts
- src/runner/browser-env/vite/browser-modules/types.ts
- src/worker/browser-env/runner/test-runner/index.ts
- test/src/worker/browser-env/runner/test-runner/index.ts
- move to @testplane/webdriverio@9.5.19
- return previous types which was modified in https://github.com/gemini-testing/testplane/pull/1067, because in new version of wdio I fixed some bugs
> chore: up @testplane/webdriverio from to 9.5.19

- src/runner/browser-runner.ts
- src/runner/index.ts
- src/runner/test-runner/insistant-test-runner.js
- src/runner/test-runner/regular-test-runner.js
- src/runner/test-runner/skipped-test-runner.js
- src/runner/types.ts
- src/worker/runner/test-runner/index.js
- src/worker/runner/test-runner/runner.ts
- test/src/runner/browser-runner.js
We had:
- "Runner" pure abstract class at "runner/runner.ts" 
- "Runner" pure abstract class at "worker/runner/test-runner/runner.ts"
- "Runner" class at "worker/runner/index.js"
Now we only have one "Runner"
> chore: remove unused code
